  
name: Releases Action

on: 
  create

jobs:
  Releases:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1.4.0
      with:
        dotnet-version: '3.1.100'
    - name: build
      run: dotnet build
    - name: publish
      run: dotnet publish test1.NETCore3/test1.NETCore3.csproj /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary /property:PublishSingleFile=true /property:PublishTrimmed=true --configuration=Release --runtime=win-x64 --self-contained=true
    - uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "**/publish/**.exe"
        tags: true
        draft: false
        verbose: true

